<?php

use App\Models\Employee;
use App\Models\EmployeeLog;
use Carbon\Carbon;
use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

Artisan::command('employee-logs:delete-old', function () {
    $cutoff = Carbon::now()->subMonth();

    $deleted = EmployeeLog::query()
        ->where('created_at', '<', $cutoff)
        ->delete();

    $this->info("Deleted {$deleted} employee log(s) older than one month.");
})->purpose('Delete employee logs older than one month from database');

Artisan::command('logs:remove-all', function () {
    $logsPath = storage_path('logs');

    if (! File::exists($logsPath)) {
        $this->warn('Logs directory does not exist.');
        return;
    }

    $removed = 0;
    foreach (File::files($logsPath) as $file) {
        File::delete($file->getPathname());
        $removed++;
    }

    $this->info("Removed {$removed} log file(s) from storage/logs.");
})->purpose('Remove all log files from storage/logs');

Artisan::command('employees:insert {count}', function (int $count) {
    if ($count < 1) {
        $this->error('Count must be at least 1.');
        return;
    }

    $inserted = 0;
    $now = now();

    $this->info("Inserting {$count} employee record(s)...");
    $bar = $this->output->createProgressBar($count);
    $bar->start();

    $founder = Employee::query()->where('is_founder', true)->first();

    // Ensure there is exactly one founder candidate in the hierarchy.
    if (! $founder && $inserted < $count) {
        $suffix = uniqid();
        $founder = Employee::create([
            'name' => 'Founder '.$suffix,
            'email' => "founder_{$suffix}@example.com",
            'salary' => random_int(8000, 15000),
            'salary_changed_at' => $now,
            'is_founder' => true,
            'manager_id' => null,
            'founder_key' => 1,
        ]);

        $inserted++;
        $bar->advance();
    }

    $managerIds = Employee::query()->pluck('id')->all();

    while ($inserted < $count) {
        $suffix = uniqid();
        $managerId = $managerIds[array_rand($managerIds)];

        $employee = Employee::create([
            'name' => fake()->name(),
            'email' => "employee_{$suffix}@example.com",
            'salary' => random_int(1000, 9000),
            'salary_changed_at' => $now,
            'is_founder' => false,
            'manager_id' => $managerId,
            'founder_key' => null,
        ]);

        $managerIds[] = $employee->id;
        $inserted++;
        $bar->advance();
    }

    $bar->finish();
    $this->newLine();
    $this->info("Inserted {$inserted} employee record(s) successfully.");
})->purpose('Insert a given number of employee records with a progress bar');

Artisan::command('db:export-sql {--path=}', function () {
    $defaultConnection = config('database.default');

    if ($defaultConnection !== 'sqlite') {
        $this->error('This command currently supports sqlite connection only.');
        return;
    }

    $databasePath = config('database.connections.sqlite.database');
    if (! $databasePath || ! File::exists($databasePath)) {
        $this->error('SQLite database file not found.');
        return;
    }

    $exportDir = storage_path('app/exports');
    File::ensureDirectoryExists($exportDir);

    $customPath = $this->option('path');
    $outputPath = $customPath
        ? (str_starts_with($customPath, '/') ? $customPath : base_path($customPath))
        : $exportDir.'/database_'.now()->format('Ymd_His').'.sql';

    $lines = [];
    $lines[] = '-- SQL export generated by db:export-sql';
    $lines[] = '-- Generated at: '.now()->toDateTimeString();
    $lines[] = 'PRAGMA foreign_keys=OFF;';
    $lines[] = 'BEGIN TRANSACTION;';
    $lines[] = '';

    $tables = DB::select("
        SELECT name, sql
        FROM sqlite_master
        WHERE type = 'table'
          AND name NOT LIKE 'sqlite_%'
        ORDER BY name
    ");

    foreach ($tables as $table) {
        if (! $table->sql) {
            continue;
        }

        $tableName = $table->name;
        $lines[] = '-- Table: '.$tableName;
        $lines[] = $table->sql.';';

        $rows = DB::table($tableName)->get();
        foreach ($rows as $row) {
            $values = [];
            foreach ((array) $row as $value) {
                if ($value === null) {
                    $values[] = 'NULL';
                } elseif (is_int($value) || is_float($value)) {
                    $values[] = (string) $value;
                } else {
                    $values[] = "'".str_replace("'", "''", (string) $value)."'";
                }
            }

            $lines[] = "INSERT INTO \"{$tableName}\" VALUES (".implode(', ', $values).");";
        }

        $lines[] = '';
    }

    $lines[] = 'COMMIT;';
    $lines[] = '';

    File::put($outputPath, implode(PHP_EOL, $lines));

    $this->info('Database exported successfully.');
    $this->line('File: '.$outputPath);
})->purpose('Export the entire sqlite database to a SQL file');

Artisan::command('employees:export-json {--path=}', function () {
    $exportDir = storage_path('app/exports');
    File::ensureDirectoryExists($exportDir);

    $customPath = $this->option('path');
    $outputPath = $customPath
        ? (str_starts_with($customPath, '/') ? $customPath : base_path($customPath))
        : $exportDir.'/employees_'.now()->format('Ymd_His').'.json';

    $employees = Employee::with('manager:id,name,email', 'subordinates:id,name,email,manager_id')
        ->orderBy('id')
        ->get();

    $payload = [
        'generated_at' => now()->toISOString(),
        'count' => $employees->count(),
        'employees' => $employees,
    ];

    File::put($outputPath, json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

    $this->info('Employees exported successfully.');
    $this->line('File: '.$outputPath);
})->purpose('Export all employee data to a JSON file');
